services:
  gateway:
    image: 597819998313.dkr.ecr.ap-southeast-2.amazonaws.com/gateway-service:latest
    container_name: gateway
    ports:
      - "80:8080"
    environment:
      SPRING_APPLICATION_NAME: gateway
      SPRING_CONFIG_IMPORT: optional:configserver:
      EUREKA_CLIENT_ENABLED: false
      SPRING_CLOUD_DISCOVERY_ENABLED: false
      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: employee-service
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://employee:8080
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/api/employees/**
    depends_on:
      - employee
    restart: always

  employee:
    image: 597819998313.dkr.ecr.ap-southeast-2.amazonaws.com/employee-service:latest
    container_name: employee
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_NAME: employee
      SERVER_PORT: 8080
      SPRING_CONFIG_IMPORT: optional:configserver:
      EUREKA_CLIENT_ENABLED: false
      SPRING_CLOUD_DISCOVERY_ENABLED: false
    restart: always
