server:
  server:
  port: 8081


spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

    gateway:
      routes:
        - id: employee-service
          uri: http://employee-service:8081
          predicates:
            - Path=/employee/**
          filters:
            - StripPrefix=1

  main:
    web-application-type: reactive


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
