server:
  port: 8084

spring:
  cloud:
    config:
      enabled: false   # <--- ADD THIS
    gateway:
      routes:
      - id: employee-service
        uri: http://localhost:8085
        predicates:
        - Path=/employee-service/**

management:
  endpoints:
    web:
      exposure:
        include: health,mappings
