server:
  port: 8084

spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

  main:
    web-application-type: reactive

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
