server:
  port: 8085
  servlet:
    context-path: /employee-service

spring:
  application:
    name: employee-service
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: mappings,health
      base-path: /
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
