server:
  port: 8085
  servlet:
    context-path: /employee-service

spring:
  cloud:
    config:
      enabled: false   # <--- ADD THIS

management:
  endpoints:
    web:
      exposure:
        include: health,mappings
