server:
  port: 8085
  servlet:
    context-path: /employee-service

management:
  tracing:
    sampling:
      probability: 0.0   
  endpoints:
    web:
      exposure:
        include: health,mappings
