name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      # Login to AWS ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      # Build Gateway Service
      - name: Build Gateway Docker Image
        run: |
          docker build \
          -f gateway-service/Dockerfile \
          -t gateway-service .


      # Build Employee Service
      - name: Build Employee Docker Image
        run: |
          docker build \
          -f employee-service/Dockerfile \
          -t employee-service .


      # Tag Images
      - name: Tag Images
        run: |
          docker tag gateway-service:latest ${{ secrets.ECR_REGISTRY }}/gateway-service:latest
          docker tag employee-service:latest ${{ secrets.ECR_REGISTRY }}/employee-service:latest


      # Push Images to ECR
      - name: Push Images to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/gateway-service:latest
          docker push ${{ secrets.ECR_REGISTRY }}/employee-service:latest
